### ISSUE TITLE
Request for citation of paper: 'Bridging the Gap between Reality and Ideality of Entity Matching: A Revisiting and Benchmark Re-Construction'

### ISSUE THREAD

**Issue by tshu-w** [wbsg-uni-mannheim/wdcproducts#1]
[Our paper](https://www.ijcai.org/proceedings/2022/0552.pdf), presented at IJCAI 2022, introduces a new benchmark to assess the generalization of models on unseen entities/records at different levels. We would be grateful if you could cite our paper in your research.

**Comment by bizer** [comment]
Dear Tianshu, 
thank you very much for pointing us at your benchmark which we did not know and will of course cite in the next version of the paper. Where can we download your benchmark?
Best regards, Chris

**Comment by tshu-w** [comment]
Dear Chris,
Here is the [link](https://github.com/tshu-w/ember/tree/main/data/ali#constructed-benchmarks) to my benchmark. Please note that since our products come from Chinese e-commerce websites, the text is in Chinese.
Best regards, Tianshu

**Comment by tshu-w** [comment]
I also tried to crawl images for products in the WDC LSPM, like in [Towards Multi-modal Entity Resolution for Product Matching](https://dbs.uni-leipzig.de/en/publication/title/towards_multi_modal_entity_resolution_for_product_matching). However, many of the products were quite old and the image quality was low, so I ended up not releasing anything. This is my [code](https://gist.github.com/tshu-w/7250b88491fc7bdbfd02bc56602da63b) at that time.
